### ISSUE TITLE
test delayed response without calling `.pause()`

### ISSUE THREAD

**Issue by gr2m** [gr2m/http-recorder#18]
> For example, I have a feeling the [693fc94](https://github.com/gr2m/http-recorder/commit/693fc940c166e6e3efdf2415cd0b4a9ea916e1f8) test case isn't exactly right. You're calling `response.pause` in the user's code, but that's not necessary. As a user you can do the following and get the expected output:
> 
> ```js
> var Http = require("http")
> 
> Http.get("http://example.com", function(res) {
> 	setTimeout(function() {
> 		res.on("data", (data) => console.log("Data:", data.toString()))
> 	}, 500)
> })
> ```
> 
> The hook into response's `data` event in the recording code is the thing that changes behavior — it immediately unpauses the stream. I suppose you could call `res.pause` in the recording code, but I have a suspicion that may then break automatic unpausing on `data` the user code does.
—https://github.com/gr2m/http-recorder/issues/3#issuecomment-999501190

**Comment by gr2m** [comment]
@moll you have been right about this one. I started a pull request in #23. 

Any idea how to get the response data without consuming the response?

I tried `response.pipe(passthrough)`

```diff
-        response.on("data", (chunk) => {
-          responseBodyChunks.push(Buffer.from(chunk));
-        });
+        const passThrough = new stream.PassThrough();
+        passThrough.on("data", (chunk) => {
+          responseBodyChunks.push(Buffer.from(chunk));
+        });
+        response.pipe(passThrough);
```


my understand was that this would not consume the response, but that does not resolve the problem.

I tried https://github.com/mcollina/cloneable-readable to clone the response, that also did not help.

Any other idea I could try, which doesn't require to monkey patch yet another API?

**Comment by moll** [comment]
> Any idea how to get the response data without consuming the response?
> I tried response.pipe(passthrough)
> my understand was that this would not consume the response, but that does not resolve the problem.

Given piping is semantically (not necessarily operationally) equivalent to reading and writing by hand, it has to drain the source. Otherwise streams wouldn't be able to handle larger file downloads, for example, without running out of memory. The operational difference probably comes from back-pressure --- piping handles the constant pausing and unpausing for us.

> Any other idea I could try, which doesn't require to monkey patch yet another API?

Which API did you plan to patch next? You may be able to hook into something deeper --- like the part that writes into the ReadableStream in the first place. The approach of trying to hook on the receiver side, like a regular user, feels fragile and is very likely to change the stream behavior. Don't forget there are two methods of reading from a stream --- the push and pull method.

**Comment by gr2m** [comment]
> Which API did you plan to patch next?

I tried monkeypatching `response.on` itself, but that also didn't work. 

Bummer, I fear this will complicate things quite a bit.

> Don't forget there are two methods of reading from a stream --- the push and pull method.

Can you elaborate a bit? I successfully avoided working with streams 🤣 I tried a few times but cannot fully wrap my head around them

Thank you for all your help, I really appreciate it. I'm learning a lot

**Comment by gr2m** [comment]
Oh I think I found a pretty good explanation here: https://www.freecodecamp.org/news/node-js-streams-everything-you-need-to-know-c9141306be93/#paused-and-flowing-modes-of-readable-streams

**Comment by gr2m** [comment]
> > Which API did you plan to patch next?
> 
> I tried monkeypatching `response.on` itself, but that also didn't work.

It worked by patching `response.emit`.

Also nearly all my tests were incorrect. They didn't consume their responses, without the calling `HttpRecorder.enable()`, the process would just hang. That might have also been the problem with my previous attempts

**Comment by moll** [comment]
You're welcome.

> > Don't forget there are two methods of reading from a stream --- the push and pull method.
> Can you elaborate a bit?

I take you've found out by now. I was just about to say that patching `emit` surely wouldn't work for the pulling form, but saw you made https://github.com/gr2m/http-recorder/pull/24. ^_^

**Comment by moll** [comment]
Ah, I found this sentence in the Node.js Streams documentation (reading from a local copy, so can't link)
> If the readable.read() method returns a chunk of data, a 'data' event will also be emitted.

Didn't know that. That sure simplified the approach you took.
